version: "3.9"
networks:
  laravel:

services:
  nginx:
    build: ./.docker/nginx
    restart: always
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - "./:/var/www/html"
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3307"
    volumes:
      - "./.docker/mysql:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build: ./.docker/php
    container_name: php
    volumes:
      - "./:/var/www/html"
    networks:
      - laravel